name: app

type: 'nodejs:14'

dependencies:
  nodejs:
    pm2: "^4.5.6"

web:
  commands:
    start: "PM2_HOME=/app/run pm2 start index.js --no-daemon"

disk: 512

mounts:
  run:
    source: local
    source_path: run